In [920]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [921]:
df = sns.load_dataset("titanic")

In [922]:
df.shape

(891, 15)

In [923]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [924]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [925]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [926]:
df.drop(["deck","adult_male","who","embark_town","alive","class"],axis = 1,inplace = True)

In [927]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [928]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [929]:
df["age"].fillna(df["age"].mean(),inplace = True)

In [930]:
df.dropna(subset = ["embarked"],inplace = True)

In [931]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [932]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [933]:
df_encode = pd.get_dummies(df,drop_first=True)
df_encode

,survived,pclass,age,sibsp,parch,fare,alone,sex_male,embarked_Q,embarked_S
0,0,3,22.000000,1,0,7.2500,False,True,False,True
1,1,1,38.000000,1,0,71.2833,False,False,False,False
2,1,3,26.000000,0,0,7.9250,True,False,False,True
3,1,1,35.000000,1,0,53.1000,False,False,False,True
4,0,3,35.000000,0,0,8.0500,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,True,True,False,True
887,1,1,19.000000,0,0,30.0000,True,False,False,True
888,0,3,29.699118,1,2,23.4500,False,False,False,True
889,1,1,26.000000,0,0,30.0000,True,True,False,False
890,0,3,32.000000,0,0,7.7500,True,True,True,False

In [934]:
df_encode = df_encode.astype(int)
df_encode

,survived,pclass,age,sibsp,parch,fare,alone,sex_male,embarked_Q,embarked_S
0,0,3,22,1,0,7,0,1,0,1
1,1,1,38,1,0,71,0,0,0,0
2,1,3,26,0,0,7,1,0,0,1
3,1,1,35,1,0,53,0,0,0,1
4,0,3,35,0,0,8,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...
886,0,2,27,0,0,13,1,1,0,1
887,1,1,19,0,0,30,1,0,0,1
888,0,3,29,1,2,23,0,0,0,1
889,1,1,26,0,0,30,1,1,0,0
890,0,3,32,0,0,7,1,1,1,0

In [935]:
from sklearn.preprocessing import StandardScaler

In [936]:
numerical_cols = ["age","fare","pclass"]
scaler = StandardScaler()
df_encode[numerical_cols] = scaler.fit_transform(df_encode[numerical_cols])
df_encode.head()

,survived,pclass,age,sibsp,parch,fare,alone,sex_male,embarked_Q,embarked_S
0,0,0.825209,-0.578023,1,0,-0.496733,0,1,0,1
1,1,-1.572211,0.655371,1,0,0.791539,0,0,0,0
2,1,0.825209,-0.269675,0,0,-0.496733,1,0,0,1
3,1,-1.572211,0.424109,1,0,0.429213,0,0,0,1
4,0,0.825209,0.424109,0,0,-0.476604,1,1,0,1

In [937]:
from sklearn.model_selection import train_test_split

In [938]:
x = df_encode.drop("survived",axis = 1)
y = df_encode["survived"]

In [939]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

LogisticRegression

In [940]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(x_train,y_train)

LogisticRegression()

In [941]:
y_pred = model.predict(x_test)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [942]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [943]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [944]:
accuracy_score(y_test,y_pred)

0.797752808988764

In [945]:
confusion_matrix(y_test,y_pred)

array([[89, 20],
       [16, 53]])

In [946]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83       109
           1       0.73      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

KNN

In [947]:
from sklearn.neighbors import KNeighborsClassifier

In [948]:
KNN_model = KNeighborsClassifier(n_neighbors= 5)
KNN_model.fit(x_train,y_train)

KNeighborsClassifier()

In [949]:
y_pred_KNN = KNN_model.predict(x_test)
y_pred_KNN

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [950]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [951]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [952]:
accuracy_score(y_test,y_pred_KNN)

0.7865168539325843

In [953]:
confusion_matrix(y_test,y_pred_KNN)

array([[87, 22],
       [16, 53]])

In [954]:
print(classification_report(y_test,y_pred_KNN))

              precision    recall  f1-score   support

           0       0.84      0.80      0.82       109
           1       0.71      0.77      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.78      0.78       178
weighted avg       0.79      0.79      0.79       178

In [955]:
df_encode

,survived,pclass,age,sibsp,parch,fare,alone,sex_male,embarked_Q,embarked_S
0,0,0.825209,-0.578023,1,0,-0.496733,0,1,0,1
1,1,-1.572211,0.655371,1,0,0.791539,0,0,0,0
2,1,0.825209,-0.269675,0,0,-0.496733,1,0,0,1
3,1,-1.572211,0.424109,1,0,0.429213,0,0,0,1
4,0,0.825209,0.424109,0,0,-0.476604,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...
886,0,-0.373501,-0.192588,0,0,-0.375957,1,1,0,1
887,1,-1.572211,-0.809285,0,0,-0.033760,1,0,0,1
888,0,0.825209,-0.038413,1,2,-0.174665,0,0,0,1
889,1,-1.572211,-0.269675,0,0,-0.033760,1,1,0,0
890,0,0.825209,0.192848,0,0,-0.496733,1,1,1,0

In [956]:
from sklearn.naive_bayes import GaussianNB

In [957]:
model_NB = GaussianNB()
model_NB.fit(x_train,y_train)

GaussianNB()

In [958]:
y_pred_NB = model_NB.predict(x_test)
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [959]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [960]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [961]:
accuracy_score(y_test,y_pred_NB)

0.797752808988764

In [962]:
confusion_matrix(y_test,y_pred_NB)

array([[89, 20],
       [16, 53]])

In [963]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83       109
           1       0.73      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

In [964]:
from sklearn.tree import DecisionTreeClassifier

In [965]:
model_DT = DecisionTreeClassifier(random_state = 42)
model_DT.fit(x_train,y_train)

DecisionTreeClassifier(random_state=42)

In [966]:
y_pred_DT = model_DT.predict(x_test)
y_pred_DT

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0])

In [967]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [968]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [969]:
accuracy_score(y_test,y_pred_DT)

0.797752808988764

In [970]:
confusion_matrix(y_test,y_pred_DT)

array([[89, 20],
       [16, 53]])

In [971]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83       109
           1       0.73      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

In [972]:
from sklearn.svm import SVC

In [973]:
model_SVM = SVC(kernel = "linear")
model_SVM.fit(x_train,y_train)

SVC(kernel='linear')

In [974]:
y_pred_SVM = model_SVM.predict(x_test)
y_pred_SVM

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1])

In [975]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [976]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [977]:
accuracy_score(y_test,y_pred_SVM)

0.8033707865168539

In [978]:
confusion_matrix(y_test,y_pred_SVM)

array([[90, 19],
       [16, 53]])

In [979]:
print(classification_report(y_test,y_pred_SVM))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

Cross Validation

In [980]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.000000,1,0,7.2500,S,False
1,1,1,female,38.000000,1,0,71.2833,C,False
2,1,3,female,26.000000,0,0,7.9250,S,True
3,1,1,female,35.000000,1,0,53.1000,S,False
4,0,3,male,35.000000,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,True
887,1,1,female,19.000000,0,0,30.0000,S,True
888,0,3,female,29.699118,1,2,23.4500,S,False
889,1,1,male,26.000000,0,0,30.0000,C,True
890,0,3,male,32.000000,0,0,7.7500,Q,True

In [981]:
df_encode

,survived,pclass,age,sibsp,parch,fare,alone,sex_male,embarked_Q,embarked_S
0,0,0.825209,-0.578023,1,0,-0.496733,0,1,0,1
1,1,-1.572211,0.655371,1,0,0.791539,0,0,0,0
2,1,0.825209,-0.269675,0,0,-0.496733,1,0,0,1
3,1,-1.572211,0.424109,1,0,0.429213,0,0,0,1
4,0,0.825209,0.424109,0,0,-0.476604,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...
886,0,-0.373501,-0.192588,0,0,-0.375957,1,1,0,1
887,1,-1.572211,-0.809285,0,0,-0.033760,1,0,0,1
888,0,0.825209,-0.038413,1,2,-0.174665,0,0,0,1
889,1,-1.572211,-0.269675,0,0,-0.033760,1,1,0,0
890,0,0.825209,0.192848,0,0,-0.496733,1,1,1,0

In [982]:
from sklearn.model_selection import cross_val_score

In [983]:
scores_SVM = cross_val_score(model_SVM,x,y,cv = 5,scoring = "accuracy")

In [984]:
print(scores_SVM)

[0.80337079 0.80898876 0.78651685 0.75280899 0.78531073]

In [985]:
print(scores_SVM.mean())

0.7873992255443407

In [986]:
scores_KNN = cross_val_score(KNN_model,x,y,cv = 5,scoring = "accuracy")

In [987]:
print(scores_KNN.mean())

0.797543325080937

In [988]:
scores_DT = cross_val_score(model_DT,x,y,cv = 5,scoring = "accuracy")

In [989]:
print(scores_DT.mean())

0.7907763600584016

In [990]:
scores_NB = cross_val_score(model_NB,x,y,cv = 5,scoring = "accuracy")

In [991]:
print(scores_NB.mean())

0.7727988319685141

In [992]:
print(scores_SVM.mean())

0.7873992255443407